version: '3'
services:
  shellbox:
    restart: always
    build: shellbox
    container_name: shellbox
    hostname: shellbox
    image: registry.capture.tf/wactf0x04/shellbox
    ports:
      - "22:22"
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
      - SYS_CHROOT
      - KILL
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 50M
        reservations:
          cpus: '0.05'
          memory: 20M # 0: 16.82MiB / 1: 18.58MiB / 4: 23.04MiB